source 'https://rubygems.org'

ruby '2.7.3'

abort 'Bundler version >= 2.1.4 is required' if Gem::Version.new(Bundler::VERSION) < Gem::Version.new('2.1.4')

gem 'activerecord'
gem 'activesupport'
gem 'allure-rspec'
gem 'appium_capybara'
gem 'appium_lib'
gem 'byebug'
gem 'capybara'
gem 'capybara-screenshot'
gem 'climate_control'
gem 'dotenv'
gem 'factory_bot'
gem 'faker'
gem 'faraday'
gem 'http'
gem 'mailosaur'
gem 'open-uri'
gem 'parallel_tests', '~> 3.7', '>= 3.7.1'
gem 'pdf-reader'
gem 'pg'
gem 'pry'
gem 'rails'
gem 'rest-client'
gem 'retryable'
gem 'rspec'
gem 'rspec-retry'
gem 'rubocop', '~> 1.13', require: false
gem 'selenium-webdriver'
gem 'simplecov'
gem 'site_prism'
gem 'spring-commands-rspec'
gem 'spring-watcher-listen'
gem 'timecop'
gem 'vcr'
gem 'webmock'
gem 'websocket-driver'
gem 'yaml'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]