server: "hub.crossbrowsertesting.com:80/wd/hub"

common_caps:
  "record_video": true
  "record_network": false
  "screenResolution": "1920x1200"

windows_chrome_caps:
  "platform": "Windows 10"
  "browserName": "Chrome"

windows_firefox_caps:
  "platform": "Windows 10"
  "browserName": "Firefox"

windows_edge_caps:
  "platform": "Windows 10"
  "browserName": "Edge"

mac_chrome_caps:
  "platform": "Mac OSX 10.15"
  "browserName": "Chrome"

mac_firefox_caps:
  "platform": "Mac OSX 10.15"
  "browserName": "Firefox"

mac_safari_caps:
  "platform": "MacOS 11.0"
  "browserName": "Safari"
  "version": "14"

android_chrome_caps:
  "deviceName": "Galaxy S10"
  "platformName": "Android"
  "platformVersion": "10.0"
  "browserName": "Chrome"
  "deviceOrientation": "portrait"
  "screenResolution": "1080x2280"

ios_safari_caps:
  "deviceName": "iPhone 11 Pro"
  "platformName": "iOS"
  "platformVersion": "13.2"
  "browserName": "Safari"
  "deviceOrientation": "portrait"
  "screenResolution": "1125x2436"